const listaLatexFrentesNetcolor = [
    { price: 5600.75, codigo: 2090, name: "LATEX FRENTES IMPER. x 1 lt. BLANCO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 20661.62, codigo: 2091, name: "LATEX FRENTES IMPER. x 4 lts. BLANCO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 45541.93, codigo: 2092, name: "LATEX FRENTES IMPER. x 10 lts. BLANCO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 151503.28, codigo: 2093, name: "LATEX FRENTES x 20 lts. BLANCO SHER", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 5168.13, codigo: 2100, name: "LATEX FRENTES IMPER. x 1 lt. ROJO TEJA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 18056.66, codigo: 2101, name: "LATEX FRENTES IMPER. x 4 lts. ROJO TEJA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 39041.35, codigo: 2102, name: "LATEX FRENTES IMPER. x 10 lts. ROJO TEJA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2266.00, codigo: 2103, name: "LATEX FRENTES IMPER. x 250 cc. ROJO TEJA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 5168.13, codigo: 2104, name: "LATEX FRENTES x 1 l. BORGOÑA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 18882.78, codigo: 2105, name: "LATEX FRENTES x 4 lts. BORGOÑA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 40827.55, codigo: 2106, name: "LATEX FRENTES x 10 lts. BORGOÑA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 76544.66, codigo: 2107, name: "LATEX FRENTES x 20 lts. BORGOÑA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    ///
    { price: 5856.99, codigo: 2108, name: "LATEX FRENTES IMPER. x 1 l. GRIS CEMENTO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 21606.93, codigo: 2109, name: "LATEX FRENTES IMPER. x 4 lts. GRIS CEMENTO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 47625.55, codigo: 2110, name: "LATEX FRENTES IMPER. x 10lts. GRIS CEMENTO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3113.07, codigo: 2111, name: "LATEX FRENTES IMER. x 250 CC. GRIS CEMENTO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 8798.67, codigo: 2112, name: "LATEX FRENTES IMPER. x 1 l. VERDE MANZANA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 33311.02, codigo: 2113, name: "LATEX FRENTES IMPER. x 4 lts. VERDE MANZANA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 76655.07, codigo: 2114, name: "LATEX FRENTES IMPER. x 10 lts. VERDE MANZANA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3207.01, codigo: 2115, name: "LATEX FRENTES IMPER. x 250l CC. VERDE MANZANA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 5856.99, codigo: 2116, name: "LATEX FRENTES x 1 l. VERDE SAFARI", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 21606.93, codigo: 2117, name: "LATEX FRENTES x 4 lts. VERDE SAFARI", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 47625.55, codigo: 2118, name: "LATEX FRENTES x 10 lts. VERDE SAFARI", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3113.07, codigo: 2119, name: "LATEX FRENTES x 250 CC. VERDE SAFARI", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    ///
    { price: 3230.08, codigo: 2120, name: "LATEX FRENTES x 1 l. NEGRO EBANO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 11801.74, codigo: 2121, name: "LATEX FRENTES x 4 lts. NEGRO EBANO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 25517.22, codigo: 2122, name: "LATEX FRENTES x 10 lts. NEGRO EBANO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 47840.41, codigo: 2123, name: "LATEX FRENTES x 20 lts. NEGRO EBANO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 5168.13, codigo: 2124, name: "LATEX FRENTES IMPER. x 1 l. OCRE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 18882.78, codigo: 2125, name: "LATEX FRENTES  IMPER. x 4 lts. OCRE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 40829.20, codigo: 2126, name: "LATEX FRENTES IMPER x 10 lts. OCRE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2266.00, codigo: 2127, name: "LATEX FRENTES IMPER. x 250 cc. OCRE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 5856.99, codigo: 2128, name: "LATEX FRENTES IMPER. x 1l. AZUL TRAFUL", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 21606.93, codigo: 2129, name: "LATEX FRENTES IMPER. x 4 lts. AZUL TRAFUL", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 47625.55, codigo: 2130, name: "LATEX FRENTES IMPER. x 10 lts. AZUL TRAFUL", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2429.15, codigo: 2131, name: "LATEX FRENTES IMPER. x 250 cc. AZUL TRAFUL", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    ///
    { price: 5168.13, codigo: 2132, name: "LATEX FRENTES IMPER x 1 l. MARRON AFRICANO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 18882.78, codigo: 2133, name: "LATEX FRENTES IMPER. x 4 lts. MARRON AFRICANO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 40827.55, codigo: 2134, name: "LATEX FRENTES IMPER. x 10 lts. MARRON AFRICANO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2266.00, codigo: 2135, name: "LATEX FRENTES IMPER. x 250 cc. MARRON AFRICANO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 8798.67, codigo: 2140, name: "LATEX FRENTES IMPER x 1l. AMARILLO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 33311.02, codigo: 2141, name: "LATEX FRENTES IMPER. x 4 lts. AMARILLO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 76655.07, codigo: 2142, name: "LATEX FRENTES IMPER. x 10 lts. AMARILLO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3207.01, codigo: 2143, name: "LATEX FRENTES IMPER. x 250 cc. AMARILLO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 13856.38, codigo: 2144, name: "LATEX FRENTES IMPER. x 1 l. MAGENTA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 53314.45, codigo: 2145, name: "LATEX FRENTES IMPER. x 4 lts. MAGENTA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 127874.91, codigo: 2146, name: "LATEX FRENTES IMPER. x 10 lts. MAGENTA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3207.01, codigo: 2147, name: "LATEX FRENTES IMPER. x 250 cc. MAGENTA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'}
];

module.exports = listaLatexFrentesNetcolor;