const listaPinturasEnAerosol = [
    { price: 2449.60, codigo: 2010, name: "PINT. AEROSOL x 240cc. AMARILLO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2011, name: "PINT. AEROSOL x 240cc. ANTIOXIDO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2012, name: "PINT. AEROSOL x 240cc. AZUL MARINO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2013, name: "PINT. AEROSOL x 240cc. BERMELLON", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2014, name: "PINT. AEROSOL x 240cc. BLANCO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2015, name: "PINT. AEROSOL x 240cc. BLANCO MATE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2016, name: "PINT. AEROSOL x 240cc. CELESTE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3241.60, codigo: 2017, name: "PINT. AEROSOL x 240cc. GRAFITO LLANTAS", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2018, name: "PINT. AEROSOL x 240cc. GRIS OSCURO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2019, name: "PINT. AEROSOL x 240cc. NEGRO MATE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2020, name: "PINT. AEROSOL x 240cc. NEGRO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2021, name: "PINT. AEROSOL x 240cc. NARANJA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2022, name: "PINT. AEROSOL x 240cc. VIOLETA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2023, name: "PINT. AEROSOL X 240cc. AZUL TRAFUL", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2024, name: "PINT. AEROSOL x 240c.c. NEGRO SATINADO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    ///
    { price: 2449.60, codigo: 2025, name: "PINT. AEROSOL x 240cc. TABACO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2026, name: "PINT. AEROSOL x 240c.c. BLANCO SATINADO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2027, name: "PINT. AEROSOL x 240cc. VERDE INGLES", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2910.40, codigo: 2028, name: "PINT. AERO x 240 cc. FIJ. PROTE. TRANS. (laca)", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 2449.60, codigo: 2029, name: "PINT. AEROSOL x 240cc. BARNIZ TRANSP.", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3406.40, codigo: 2030, name: "PINT. AEROSOL X 240 cc. CROMADO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3764.80, codigo: 2033, name: "PINT. AEROSOL x 240cc. METALIZADO ORO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3240.00, codigo: 2034, name: "PINT. AEROSOL x 240cc. METALIZADO PLATA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3547.20, codigo: 2035, name: "PINT. AEROSOL x 240cc. ALTA TEMP. ALUMINIO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 3888.00, codigo: 2036, name: "PINT. AEROSOL x 240cc. ALTA TEMP. NEGRO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6956.80, codigo: 2039, name: "PINT. AEROSOL EPOXI X 440", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 4243.20, codigo: 2043, name: "PINT. AEROSOL FLUOR. x240cc. AMARILLO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 4243.20, codigo: 2044, name: "PINT. AEROSOL FLUOR. x240cc. NARANJA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 4243.20, codigo: 2046, name: "PINT. AEROSOL FLUOR. x240cc. ROJO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 4243.20, codigo: 2047, name: "PINT. AEROSOL FLUOR. x240cc. VERDE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    ///
    { price: 4243.20, codigo: 2048, name: "PINT.AEROSOL FLUORX 240cc. ROSA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 5652.80, codigo: 2049, name: "PINT. AEROSOL EFECTO ESMERILADO X 440", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 5664.00, codigo: 2051, name: "ESPUMA DE POLIURETANO EXPANDIDO 293 gs. 300 ml", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6942.48, codigo: 4500, name: "PINT. AEROSOL X 440 AMARILLO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6942.48, codigo: 4560, name: "PINT. AEROSOL X 440 BLANCO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6942.48, codigo: 4562, name: "PINT. AEROSOL X 440 BLANCO MATE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6942.48, codigo: 4564, name: "PINT. AEROSOL X 440 BLANCO SATINADO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6942.48, codigo: 4576, name: "PINT. AEROSOL X 440 NEGRO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6942.48, codigo: 4578, name: "PINT. AEROSOL X 440 NEGRO MATE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6942.48, codigo: 4580, name: "PINT. AEROSOL X 440 NEGRO SATINADO", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6942.48, codigo: 4596, name: "PINT. AEROSOL X 440 ROJO FURIA", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    { price: 6942.48, codigo: 4600, name: "PINT. AEROSOL X 440 BARNIZ TRANSP. BRILLANTE", imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'}
];

module.exports = listaPinturasEnAerosol;