const url = 'imagen';

const listaDeProductos = [
    { price: 1989.02, codigo: '0998', name: 'ALCOHOL FINO X 500 cc', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3388.00, codigo: '1000', name: 'ALCOHOL FINO X 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2589.97, codigo: '1001', name: 'ALCOHOL DE QUEMAR x 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 8075.50, codigo: '1002', name: 'CARBURO  DE CALCIO x 120 kg.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 8596.50, codigo: '1003', name: 'CARBURO DE CALCIO SUELTO X kg.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 10375.63, codigo: '1004', name: 'ALUMBRE DE POTACIO X 1 kg', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1391.25, codigo: '1005', name: 'SODA CAUSTICA LIQUIDA x 900 cc.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1140.00, codigo: '1007', name: 'ACIDO MURIATICO x 1 lt', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3400.00, codigo: '1008', name: 'ACIDO MURIATICO x 5 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1346.40, codigo: '1009', name: 'DESENGRASANTE ALCALINO EN GRANOS X 1 kg.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 6125.39, codigo: '1010', name: 'DESENGRASANTE ALCALINO LIQUIDO X 1 lt', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3899.80, codigo: '1011', name: 'DESOXIDANTE FOSFATIZANTE X 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3062.04, codigo: '1015', name: 'DESTAPA CAÑERIAS LIQUIDO X 900 cc', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 865.15, codigo: '1040', name: 'SELLADOR DE POLIPROPILENO X 25 cc.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 4868.98, codigo: '1042', name: 'SELLADOR DE SILICONA PAR FISURAS X 280BL', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 7488.00, codigo: '1045', name: 'SELLADOR PARA CAÑOS DE GAS X 15 grs.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 13311.00, codigo: '1046', name: 'SELLADOR PARA CAÑOS DE GAS X 50 grs.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1870.00, codigo: '1048', name: 'ADHESIVO DE CONTACTO X 125 cc.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2420.80, codigo: '1050', name: 'ADHESIVO PVC X 100 C. C.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1172.80, codigo: '1056', name: 'LITARGIRIO X 100 grs.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 544.00, codigo: '1060', name: 'GLICERINA PURA X 100 grs', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 646.40, codigo: '1066', name: 'CAÑAMO PEINODO FINO X 20 grs.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 953.60, codigo: '1068', name: 'GRASA DE LITIO X 125 grs.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 560.00, codigo: '1070', name: 'GRASA GRAFITADA X 40 grs.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 680.00, codigo: '1075', name: 'DECAPANTE X 70 GS.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 7400.61, codigo: '1076', name: 'FUNDENTE DE PLATA X 100 grs.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 533.34, codigo: '1080', name: 'MASILLA PARA VIDRIOS Y SANITARIOS X 500 grs.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 800.08, codigo: '1081', name: 'MASILLA PARA VIDRIOS Y SANITARIOS X 1 kg', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto'},
    ///
    { price: 1675.35, codigo: '1120', name: 'AGUARRAS MINERAL x 900 cc.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 8704.17, codigo: '1121', name: 'AGUARRAS MINERAL x 5 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 295596.00, codigo: '1122', name: 'AGUARRAS MINERAL x 200 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 5188.23, codigo: '1124', name: 'SOLVENTE INDUSTRIAL  x 900 cc', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 24945.12, codigo: '1125', name: 'SOLVENTE INDUSTRIAL x 5 LT.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2240.00, codigo: '1128', name: 'THINNER PARA LIMPIEZA X 800 cc.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2268.00, codigo: '1129', name: 'THINNER X 500 cc.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3393.60, codigo: '1130', name: 'THINNER x 900 cc.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 17377.60, codigo: '1131', name: 'THINNER x 5 lts', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 618120.00, codigo: '1133', name: 'THINNER x 200lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 4151.35, codigo: '1134', name: 'THINNER SELLO DE ORO x 900 cc.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 21705.75, codigo: '1135', name: 'THINNER SELLO DE ORO x 5 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 668304.00, codigo: '1137', name: 'THINNER SELLO DE ORO x 200 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1969.60, codigo: '1140', name: 'KEROSENE x 900 cc.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 10808.00, codigo: '1141', name: 'KEROSENE x 5 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 43635.60, codigo: '1144', name: 'REMOVEDOR GEL x 4 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 7129.80, codigo: '1146', name: 'REMOVEDOR EN GEL X 1/2 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 10404.00, codigo: '1148', name: 'REMOVEDOR EN GEL X 1 lt', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    ///
    { price: 2994.54, codigo: '1150', name: 'ACEITE DE LINO X 900 cc', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 15218.04, codigo: '1151', name: 'ACEITE DE LINO X 5 lts', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 483021.00, codigo: '1152', name: 'ACEITE DE LINO X 200 lts', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    ///
    { price: 2821.38, codigo: '1250', name: 'CONVERTIDOR DE OXIDO BLANCO X 1/4 lt', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 4307.87, codigo: '1251', name: 'CONVERTIDOR DE OXIDO BLANCO X 1/2 lt', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 6926.54, codigo: '1252', name: 'CONVERTIDOR DE OXIDO BLANCO X 1 lt', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2532.47, codigo: '1260', name: 'CONVERTIDOR DE OXIDO AL CROMATO BLANCO x 1/4 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3782.16, codigo: '1261', name: 'CONVERTIDOR DE OXIDO AL CROMATO BLANCO x 1/2lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 5949.02, codigo: '1262', name: 'CONVERTIDOR DE OXIDO AL CROMATO BLANCO x 1lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 20587.56, codigo: '1263', name: 'CONVERTIDOR DE OXIDO AL CROMATO BLANCO x 4lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 104110.85, codigo: '1264', name: 'CONVERTIDOR DE OXIDO BLANCO x 20lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2697.94, codigo: '1265', name: 'CONVERTIDOR DE OXIDO NEGRO x 1/4 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 4119.40, codigo: '1266', name: 'CONVERTIDOR DE OXIDO NEGRO x 1/2 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 6623.51, codigo: '1267', name: 'CONVERTIDOR DE OXIDO NEGRO x 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 23285.50, codigo: '1268', name: 'CONVERTIDOR DE OXIDO NEGRO x 4 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 108880.69, codigo: '1269', name: 'CONVERTIDOR DE OXIDO NEGRO x 20 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3277.70, codigo: '1270', name: 'CONVERTIDOR DE OXIDO GRIS x 1/4 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3563.61, codigo: '1271', name: 'CONVERTIDOR DE OXIDO GRIS x 1/2 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 8494.18, codigo: '1272', name: 'CONVERTIDOR DE OXIDO GRIS x 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 28696.76, codigo: '1273', name: 'CONVERTIDOR DE OXIDO GRIS x 4lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 136423.06, codigo: '1274', name: 'CONVERTIDOR DE OXIDO GRIS x 20 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 8092.66, codigo: '1287', name: 'ANTIOXIDO AL CROMATO GRIS  x 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 28696.76, codigo: '1288', name: 'ANTIOXIDO AL CROMATO GRIS x 4 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 104110.85, codigo: '1289', name: 'ANTIOXIDO AL CROMATO GRIS x 20 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 90106.72, codigo: '1299', name: 'Antioxido al Cromato gris 020 x 20 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2532.47, codigo: '1300', name: 'Antioxido al Cromato negro x 1/4 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3782.16, codigo: '1301', name: 'Antioxido al Cromato negro x 1/2 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 5949.02, codigo: '1302', name: 'Antioxido al Cromato negro x 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 20587.56, codigo: '1303', name: 'Antioxido al Cromato negro x 4 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 106177.93, codigo: '1304', name: 'Antioxido al Cromato negro x 20 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1058.84, codigo: '1311', name: 'Antioxido al cromato rojo x 1/4 l.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3240.05, codigo: '1312', name: 'Antioxido al cromato rojo x 1/2 l.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 5328.99, codigo: '1313', name: 'Antioxido al cromato rojo x 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 18451.80, codigo: '1314', name: 'Antioxido al Cromato rojo x 4 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 40771.52, codigo: '1315', name: 'Antioxido al cromato rojo x 10 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    //////
    { price: 3265.26, codigo: '1392', name: 'FIJADOR SELLADOR AL AGUA CONCENTRADO x 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 11329.15, codigo: '1393', name: 'FIJADOR SELLADOR AL AGUA CONCENTRADO x 4 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 22371.48, codigo: '1394', name: 'FIJADOR SELLADOR AL AGUA CONCENTRADO x 10 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 5214.65, codigo: '1396', name: 'FIJADOR AL AGUARRAS x 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 17599.65, codigo: '1397', name: 'FIJADOR AL AGUARRAS x 4 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3366.12, codigo: '1399', name: 'FONDO BLANCO PARA MADERAS x 1/2 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 4965.66, codigo: '1400', name: 'FONDO BLANCO PARA MADERAS x 1 lt.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 16917.29, codigo: '1401', name: 'FONDO BLANCO PARA MADERAS x 4 lts.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1713.00, codigo: '1403', name: 'ENDUIDO INTERIOR x 1/2', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2991.06, codigo: '1404', name: 'ENDUIDO INTERIOR x 1', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 10210.26, codigo: '1405', name: 'ENDUIDO INTERIOR x 4', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 19282.71, codigo: '1406', name: 'ENDUIDO INTERIOR x 10', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 3348.79, codigo: '1408', name: 'ENDUIDO EXTERIOR x 1', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 11623.84, codigo: '1409', name: 'ENDUIDO EXTERIOR x 4', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 22828.49, codigo: '1410', name: 'ENDUIDO EXTERIOR x 10', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1936.78, codigo: '1412', name: 'ENDUIDO EXTERIOR  X 1/2', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 1483.20, codigo: '1414', name: 'MASILLA PARA DURLOCK X 1.80 KG.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 6560.00, codigo: '1415', name: 'MASILLA PARA DURLOCK X 7 KG.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 13600.00, codigo: '1416', name: 'MASILLA PARA DURLOCK X 14 KG.', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 8200.98, codigo: '1420', name: 'LADRI. Y TEJAS ANTIHUMEDAD X 1 NATURAL', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 28982.38, codigo: '1421', name: 'LADRI. Y TEJAS ANTIHUMEDAD X 4 NATURAL', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 8308.19, codigo: '1423', name: 'LADRI. Y TEJAS ANTIHUMEDAD X 1 CERAMICO', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 29361.23, codigo: '1424', name: 'LADRI. Y TEJAS ANTIHUMEDAD X 4 CERAMIC', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    /////
    { price: 809.43, codigo: '1450', name: 'ENTONADOR UNIVERSAL x30 cc. amarillo', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1451', name: 'ENTONADOR UNIVERSAL x30 cc. azul', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1452', name: 'ENTONADOR UNIVERSAL x30 cc. bermellon', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1453', name: 'ENTONADOR UNIVERSAL x30 cc. cedro', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1454', name: 'ENTONADOR UNIVERSAL x30 cc. ocre', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1455', name: 'ENTONADOR UNIVERSAL x30 cc. marron', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1456', name: 'ENTONADOR UNIVERSAL x30 cc. naranja', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1457', name: 'ENTONADOR UNIVERSAL x30 cc. negro', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1458', name: 'ENTONADOR UNIVERSAL x30 cc. siena', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.48, codigo: '1459', name: 'ENTONADOR UNIVERSAL x30 cc. violeta', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1460', name: 'ENTONADOR UNIVERSAL x30 cc. verde claro', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 809.43, codigo: '1461', name: 'ENTONADOR UNIVERSAL x30 cc. verde oscuro', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1462', name: 'ENTONADOR UNIVERSAL x120cc. amarillo', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1463', name: 'ENTONADOR UNIVERSAL x120cc. azul', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1464', name: 'ENTONADOR UNIVERSAL x120cc. bermellon', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1465', name: 'ENTONADOR UNIVERSAL x120cc. cedro', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1466', name: 'ENTONADOR UNIVERSAL x120cc. ocre', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1467', name: 'ENTONADOR UNIVERSAL x120cc. marron', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1468', name: 'ENTONADOR UNIVERSAL x120cc. naranja', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1469', name: 'ENTONADOR UNIVERSAL x120cc. negro', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1470', name: 'ENTONADOR UNIVERSAL x120cc. siena', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1471', name: 'ENTONADOR UNIVERSAL x120cc. violeta', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1472', name: 'ENTONADOR UNIVERSAL x120cc. verde claro', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    { price: 2163.26, codigo: '1473', name: 'ENTONADOR  UNIVERSAL x120 cc. verde oscuro', imagen: 'url', descripcion: 'Descripción del producto', category: 'Categoría del producto' },
    /////
]


module.exports = listadoDeProductos;